load:
- fundamentals
- historical-intraday

tickers:
- US.AAPL

max-parallelism: 10

fundamentals:
  s3-bucket: my-s3-bucket
  s3-prefix: fundamentals/

historical-intraday:
  s3-bucket: my-s3-bucket
  s3-prefix: historical-intraday/
  interval:  1m
  time-range:
    from:    2023-01-01 00:00:00 UTC
    to:      2023-02-01 00:00:00 UTC
    split:   24h

eodhd:
  api-key: demo

aws:
  region:  us-east-1
  profile: my-aws-profile